# Shared Config

#domain: sokoban

#root_dir: ${oc.env:LEXICON}/domains/${domain}

# Possible mode values:
# "generation" -> generate (constrained problem, optimal plan) data samples for the requested domain. 
# "simulation" -> given a constrained problem, simulate the actions of an agent that is trying to solve the problem
# "evaluation" -> run models on a generated problem
# "decision-making" -> run models on a generated problem step-by-step
# "metrics" -> get metrics from stored model answers
#
mode: generation

# Generation mode parameters
initial_seed: 5425
num_seeds: 15 # 17
#logs_dir: ${root_dir}/logs 
constraint_form:
  constraints_no: 10
  constraint_types:
    always:
      operations: [and]
      arguments_min: 1
      arguments_max: 1
    sometime:
      operations: [or, and]
      arguments_min: 1
      arguments_max: 2
    at_most_once:
      operations: [and]
      arguments_min: 1
      arguments_max: 1
    sometime_before:
      operations: [or]
      arguments_min: 1
      arguments_max: 2
    sometime_after:
      operations: [or] # [and]
      arguments_min: 1
      arguments_max: 2


# Simulation mode parameters
#data_no: 210
render: False
# Evaluation mode parameters 
#data_samples_dir: ${root_dir}/data 
#
folder_no: 1
#evaluation_data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20] 
#evaluation_data: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] 
#evaluation_data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] 
#evaluation_data: [1]
#evaluation_data: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18] 
#evaluation_data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
#evaluation_data: [11, 12, 13, 14, 15] 
evaluation_data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] 
few_shot_data: [31, 32]
#
#
# Domain specific params (that should be eventually moved elsewhere)
num_blocks: 7

# common params
